name: NodeJS with Webpack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    permissions:
      contents: write
    
    steps:
    - name: Main checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Sub checkout
      uses: actions/checkout@v3
      with:
        ripository: ReoHosokawa/type_script_sample
        path: type_script_sample
        ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

    - name: Git setting
      run: |
        cd main
        git config --local user.email "94281946+ReoHosokawa@users.noreply.github.com"
        git config --local user.name "ReoHosokawa"

    - name: Build & Commit
      run: |
        robocopy ./type_script_sample/public ./public /s
        git add ./public/* 
        git commit -m "build result commit" -a
        git pull origin main
        git push origin main
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
